target:
	javac ../source/Card.java -d ../target/classes
	javac ../source/Desk.java -d ../target/classes -classpath ../target/classes
	javac ../source/MessageHead.java -d ../target/classes
	javac ../source/Opponent.java -d ../target/classes	
	javac ../source/pokerPowerAnalysis.java -d ../target/classes -classpath ../target/classes
	javac ../source/preFlopAction.java -d ../target/classes -classpath ../target/classes
	javac ../source/actionDecision.java -d ../target/classes -classpath ../target/classes
	javac ../source/Game.java  -d ../target/classes/ -classpath ../target/classes
