target:
	javac ../source/src/huawei/texaspoker/Card.java -d ../source/classes
	javac ../source/src/huawei/texaspoker/Desk.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/MessageHead.java -d ../source/classes
	javac ../source/src/huawei/texaspoker/Opponent.java -d ../source/classes	
	javac ../source/src/huawei/texaspoker/pokerPowerAnalysis.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/historyPlayer.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/pokerStrategy.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/restCards.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/preFlopAction.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/actionDecision.java -d ../source/classes -classpath ../source/classes
	javac ../source/src/huawei/texaspoker/Game.java  -d ../source/classes/ -classpath ../source/classes
