target:
	javac ../source/src/huawei/texaspoker/Card.java -d ../target/classes
	javac ../source/src/huawei/texaspoker/Desk.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/MessageHead.java -d ../target/classes
	javac ../source/src/huawei/texaspoker/Opponent.java -d ../target/classes	
	javac ../source/src/huawei/texaspoker/pokerPowerAnalysis.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/historyPlayer.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/pokerStrategy.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/restCards.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/preFlopAction.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/actionDecision.java -d ../target/classes -classpath ../target/classes
	javac ../source/src/huawei/texaspoker/Game.java  -d ../target/classes/ -classpath ../target/classes
